#!/bin/bash

function printover {
	echo -en "\r\033[K" "$1"
	sleep 1
}

printover '         ┳━┳     '
printover '°-°)     ┳━┳     '
printover '(ヽ°-°)ヽ┳━┳     '
printover '(╯ °□°）╯︵ ┻━┻  '
printover ' (°-° )     ┻━┻  '
printover '-° )        ┻━┻  '
printover '            ┻━┻  '

echo -e "\n"
