#!/usr/bin/bash
reset="\r\033[K"

function printover {
	echo -en $reset "$1"
	sleep 1
}

printover '         ┳━┳     '
printover '°-°)     ┳━┳     '
printover '(ヽ°-°)ヽ┳━┳     '
printover '(╯ °□°）╯︵ ┻━┻  '
printover ' (°-° )     ┻━┻  '
printover '-° )        ┻━┻  '
printover '            ┻━┻  '

echo -e "\n"
